# Generated by Django 5.2.5 on 2025-08-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status'], name='pets_pet_status_2313a1_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['gender', 'size'], name='pets_pet_gender_94e44c_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['price'], name='pets_pet_price_ae1cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['location'], name='pets_pet_locatio_44d479_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['featured', 'status'], name='pets_pet_feature_a6781e_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['age_months'], name='pets_pet_age_mon_667996_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['rabies_vaccinated', 'dhpp_vaccinated'], name='pets_pet_rabies__99e2a3_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['champions_bloodline'], name='pets_pet_champio_4cc63d_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status', 'featured', '-created_at'], name='pets_pet_status_9b2630_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['gender', 'status', 'price'], name='pets_pet_gender_8db5bf_idx'),
        ),
    ]
