# Generated by Django 5.2.5 on 2025-08-14 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_pets_pet_status_2313a1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('size_category', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.breed'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['breed'], name='pets_pet_breed_i_d7cafe_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['breed', 'status', 'price'], name='pets_pet_breed_i_66b258_idx'),
        ),
    ]
