# Generated by Django 5.2.5 on 2025-08-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_breed_pet_breed_pet_pets_pet_breed_i_d7cafe_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.breed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=23, help_text='Weight in kgs', max_digits=5),
            preserve_default=False,
        ),
    ]
