# Generated by Django 5.2.5 on 2025-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_breed_alter_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='petparent',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pet_parents/avatars/'),
        ),
    ]
