# Generated by Django 5.2.5 on 2025-08-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_petparent_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='interest_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of unique people interested in this pet'),
        ),
    ]
