# Generated by Django 5.2.5 on 2025-08-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_interest_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='interest_count',
        ),
    ]
