name: CI/CD Workflow for Django + EB

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Check Django configuration
        run: python manage.py check

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python deps + EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Export DJANGO_SETTINGS_MODULE
        run: echo "DJANGO_SETTINGS_MODULE=pethub.settings" >> $GITHUB_ENV

      - name: Run migrations (only if DATABASE_URL secret exists)
        if: ${{ secrets.DATABASE_URL != '' }}
        env:
          DJANGO_SETTINGS_MODULE: pethub.settings
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python manage.py migrate --noinput

      - name: Collect static
        env:
          DJANGO_SETTINGS_MODULE: pethub.settings
        run: python manage.py collectstatic --noinput

      - name: Show collected static files (CI check)
        run: ls -la staticfiles | sed -n '1,80p' || true

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          eb init -p python-3.11 ${{ secrets.EB_APPLICATION_NAME }} --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENVIRONMENT_NAME }}
          eb deploy --staged
